package br.com.bluesoft;
// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TesteQaApplicationTests {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    private String pathDriver = "C:\\Selenium\\chromedriver.exe";

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", pathDriver);
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void cT01TestCadUsu() {
        // Test name: CT01TestCadUsu
        // Step # | name | target | value
        // 1 | open | / | 
        driver.get("http://localhost:8080/");
        // 2 | click | id=nome | 
        driver.findElement(By.id("nome")).click();
        // 3 | type | id=nome | Luis Fellipe Raimundo Santos
        driver.findElement(By.id("nome")).sendKeys("Luis Fellipe Raimundo Santos");
        // 4 | click | id=cpf | 
        driver.findElement(By.id("cpf")).click();
        // 5 | type | id=cpf | 418.377.008-42
        driver.findElement(By.id("cpf")).sendKeys("418.377.008-42");
        // 6 | click | id=celular | 
        driver.findElement(By.id("celular")).click();
        // 7 | type | id=celular | 19983475826
        driver.findElement(By.id("celular")).sendKeys("19983475826");
        // 8 | click | id=dt-nascimento | 
        driver.findElement(By.id("dt-nascimento")).click();
        // 9 | type | id=dt-nascimento | 10121994
        driver.findElement(By.id("dt-nascimento")).sendKeys("10121994");
        // 10 | click | id=btn-salvar | 
        driver.findElement(By.id("btn-salvar")).click();
        // 11 | click | id=nome | 
        driver.findElement(By.id("nome")).click();
        // 12 | click | id=nome | 
        driver.findElement(By.id("nome")).click();
        // 13 | click | id=btn-salvar | 
        driver.findElement(By.id("btn-salvar")).click();
        // 14 | click | id=input-search | 
        driver.findElement(By.id("input-search")).click();
    }

    @Test
    public void cT02TestBusca() {
        // Test name: CT02TestBusca
        // Step # | name | target | value
        // 1 | open | / | 
        driver.get("http://localhost:8080/");
        // 2 | setWindowSize | 1050x708 | 
        driver.manage().window().setSize(new Dimension(1050, 708));
        // 3 | click | id=input-search | 
        driver.findElement(By.id("input-search")).click();
        // 4 | type | id=input-search | Luis Fellipe Raimundo dos Santos
        driver.findElement(By.id("input-search")).sendKeys("Luis Fellipe Raimundo dos Santos");
        // 5 | click | css=.btn:nth-child(2) | 
        driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
        // 6 | assertElementPresent | id=app | 
        {
            List<WebElement> elements = driver.findElements(By.id("app"));
            assert (elements.size() > 0);
        }       
    }

    @Test
    public void cT03TestDelete() {
        // Test name: CT03TestDelete
        // Step # | name | target | value
        // 1 | open | / | 
        driver.get("http://localhost:8080/");       
        // 3 | click | id=input-search | 
        driver.findElement(By.id("input-search")).click();
        // 4 | type | id=input-search | Luis Fellipe Raimundo dos Santos
        driver.findElement(By.id("input-search")).sendKeys("Luis Fellipe Raimundo dos Santos");
        // 5 | click | css=.btn:nth-child(2) | 
        driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
        // 6 | click | css=.btn-danger | 
        driver.findElement(By.cssSelector(".btn-danger")).click();
        // 7 | close |  | 
        driver.close();
    }
}
